// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(RazerFFI)
import RazerFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_razer_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_razer_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureRazerCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol ControllerProtocol: AnyObject, Sendable {
    
    func catalogJson()  -> String
    
    /**
     * Supplies every coupled field for devices without hardware readback.
     * Success means sent; it must not be presented as a hardware measurement.
     */
    func configureLegacy(id: String, settings: LegacyConfiguration) throws 
    
    func devices() throws  -> [DeviceInfo]
    
    func dpi(id: String) throws  -> DpiStage
    
    func readControl(id: String, name: String) throws  -> Data
    
    func readText(id: String, name: String) throws  -> String
    
    func setDpi(id: String, x: UInt32, y: UInt32) throws  -> DpiStage
    
    func setNumber(id: String, name: String, value: UInt32) throws  -> String
    
    func setStages(id: String, stages: [DpiStage], active: UInt32) throws 
    
    func snapshot(id: String) throws  -> Snapshot
    
    func vendorId()  -> UInt16
    
    func writeControl(id: String, name: String, payload: Data) throws 
    
}
open class Controller: ControllerProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_razer_core_fn_clone_controller(self.pointer, $0) }
    }
public convenience init() {
    let pointer =
        try! rustCall() {
    uniffi_razer_core_fn_constructor_controller_new($0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_razer_core_fn_free_controller(pointer, $0) }
    }

    

    
open func catalogJson() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_razer_core_fn_method_controller_catalog_json(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Supplies every coupled field for devices without hardware readback.
     * Success means sent; it must not be presented as a hardware measurement.
     */
open func configureLegacy(id: String, settings: LegacyConfiguration)throws   {try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_razer_core_fn_method_controller_configure_legacy(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterTypeLegacyConfiguration_lower(settings),$0
    )
}
}
    
open func devices()throws  -> [DeviceInfo]  {
    return try  FfiConverterSequenceTypeDeviceInfo.lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_razer_core_fn_method_controller_devices(self.uniffiClonePointer(),$0
    )
})
}
    
open func dpi(id: String)throws  -> DpiStage  {
    return try  FfiConverterTypeDpiStage_lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_razer_core_fn_method_controller_dpi(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
})
}
    
open func readControl(id: String, name: String)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_razer_core_fn_method_controller_read_control(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterString.lower(name),$0
    )
})
}
    
open func readText(id: String, name: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_razer_core_fn_method_controller_read_text(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterString.lower(name),$0
    )
})
}
    
open func setDpi(id: String, x: UInt32, y: UInt32)throws  -> DpiStage  {
    return try  FfiConverterTypeDpiStage_lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_razer_core_fn_method_controller_set_dpi(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterUInt32.lower(x),
        FfiConverterUInt32.lower(y),$0
    )
})
}
    
open func setNumber(id: String, name: String, value: UInt32)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_razer_core_fn_method_controller_set_number(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterString.lower(name),
        FfiConverterUInt32.lower(value),$0
    )
})
}
    
open func setStages(id: String, stages: [DpiStage], active: UInt32)throws   {try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_razer_core_fn_method_controller_set_stages(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterSequenceTypeDpiStage.lower(stages),
        FfiConverterUInt32.lower(active),$0
    )
}
}
    
open func snapshot(id: String)throws  -> Snapshot  {
    return try  FfiConverterTypeSnapshot_lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_razer_core_fn_method_controller_snapshot(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
})
}
    
open func vendorId() -> UInt16  {
    return try!  FfiConverterUInt16.lift(try! rustCall() {
    uniffi_razer_core_fn_method_controller_vendor_id(self.uniffiClonePointer(),$0
    )
})
}
    
open func writeControl(id: String, name: String, payload: Data)throws   {try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_razer_core_fn_method_controller_write_control(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterString.lower(name),
        FfiConverterData.lower(payload),$0
    )
}
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeController: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Controller

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Controller {
        return Controller(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Controller) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Controller {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Controller, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeController_lift(_ pointer: UnsafeMutableRawPointer) throws -> Controller {
    return try FfiConverterTypeController.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeController_lower(_ value: Controller) -> UnsafeMutableRawPointer {
    return FfiConverterTypeController.lower(value)
}




public struct ControlRange {
    public var name: String
    public var minimum: UInt32
    public var maximum: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, minimum: UInt32, maximum: UInt32) {
        self.name = name
        self.minimum = minimum
        self.maximum = maximum
    }
}

#if compiler(>=6)
extension ControlRange: Sendable {}
#endif


extension ControlRange: Equatable, Hashable {
    public static func ==(lhs: ControlRange, rhs: ControlRange) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.minimum != rhs.minimum {
            return false
        }
        if lhs.maximum != rhs.maximum {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(minimum)
        hasher.combine(maximum)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeControlRange: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ControlRange {
        return
            try ControlRange(
                name: FfiConverterString.read(from: &buf), 
                minimum: FfiConverterUInt32.read(from: &buf), 
                maximum: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: ControlRange, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterUInt32.write(value.minimum, into: &buf)
        FfiConverterUInt32.write(value.maximum, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeControlRange_lift(_ buf: RustBuffer) throws -> ControlRange {
    return try FfiConverterTypeControlRange.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeControlRange_lower(_ value: ControlRange) -> RustBuffer {
    return FfiConverterTypeControlRange.lower(value)
}


public struct DeviceInfo {
    public var id: String
    public var name: String
    public var pid: UInt16
    public var connection: String
    public var maxDpi: UInt32
    public var minDpi: UInt32
    public var maxStages: UInt32
    public var ranges: [ControlRange]
    public var readableAttributes: [String]
    public var cachedAttributes: [String]
    public var pollRates: [UInt32]
    public var attributes: [String]
    public var dpiList: [UInt32]
    public var ledCount: UInt32
    public var tiltSupported: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, name: String, pid: UInt16, connection: String, maxDpi: UInt32, minDpi: UInt32, maxStages: UInt32, ranges: [ControlRange], readableAttributes: [String], cachedAttributes: [String], pollRates: [UInt32], attributes: [String], dpiList: [UInt32], ledCount: UInt32, tiltSupported: Bool) {
        self.id = id
        self.name = name
        self.pid = pid
        self.connection = connection
        self.maxDpi = maxDpi
        self.minDpi = minDpi
        self.maxStages = maxStages
        self.ranges = ranges
        self.readableAttributes = readableAttributes
        self.cachedAttributes = cachedAttributes
        self.pollRates = pollRates
        self.attributes = attributes
        self.dpiList = dpiList
        self.ledCount = ledCount
        self.tiltSupported = tiltSupported
    }
}

#if compiler(>=6)
extension DeviceInfo: Sendable {}
#endif


extension DeviceInfo: Equatable, Hashable {
    public static func ==(lhs: DeviceInfo, rhs: DeviceInfo) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.pid != rhs.pid {
            return false
        }
        if lhs.connection != rhs.connection {
            return false
        }
        if lhs.maxDpi != rhs.maxDpi {
            return false
        }
        if lhs.minDpi != rhs.minDpi {
            return false
        }
        if lhs.maxStages != rhs.maxStages {
            return false
        }
        if lhs.ranges != rhs.ranges {
            return false
        }
        if lhs.readableAttributes != rhs.readableAttributes {
            return false
        }
        if lhs.cachedAttributes != rhs.cachedAttributes {
            return false
        }
        if lhs.pollRates != rhs.pollRates {
            return false
        }
        if lhs.attributes != rhs.attributes {
            return false
        }
        if lhs.dpiList != rhs.dpiList {
            return false
        }
        if lhs.ledCount != rhs.ledCount {
            return false
        }
        if lhs.tiltSupported != rhs.tiltSupported {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(name)
        hasher.combine(pid)
        hasher.combine(connection)
        hasher.combine(maxDpi)
        hasher.combine(minDpi)
        hasher.combine(maxStages)
        hasher.combine(ranges)
        hasher.combine(readableAttributes)
        hasher.combine(cachedAttributes)
        hasher.combine(pollRates)
        hasher.combine(attributes)
        hasher.combine(dpiList)
        hasher.combine(ledCount)
        hasher.combine(tiltSupported)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDeviceInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DeviceInfo {
        return
            try DeviceInfo(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                pid: FfiConverterUInt16.read(from: &buf), 
                connection: FfiConverterString.read(from: &buf), 
                maxDpi: FfiConverterUInt32.read(from: &buf), 
                minDpi: FfiConverterUInt32.read(from: &buf), 
                maxStages: FfiConverterUInt32.read(from: &buf), 
                ranges: FfiConverterSequenceTypeControlRange.read(from: &buf), 
                readableAttributes: FfiConverterSequenceString.read(from: &buf), 
                cachedAttributes: FfiConverterSequenceString.read(from: &buf), 
                pollRates: FfiConverterSequenceUInt32.read(from: &buf), 
                attributes: FfiConverterSequenceString.read(from: &buf), 
                dpiList: FfiConverterSequenceUInt32.read(from: &buf), 
                ledCount: FfiConverterUInt32.read(from: &buf), 
                tiltSupported: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: DeviceInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterUInt16.write(value.pid, into: &buf)
        FfiConverterString.write(value.connection, into: &buf)
        FfiConverterUInt32.write(value.maxDpi, into: &buf)
        FfiConverterUInt32.write(value.minDpi, into: &buf)
        FfiConverterUInt32.write(value.maxStages, into: &buf)
        FfiConverterSequenceTypeControlRange.write(value.ranges, into: &buf)
        FfiConverterSequenceString.write(value.readableAttributes, into: &buf)
        FfiConverterSequenceString.write(value.cachedAttributes, into: &buf)
        FfiConverterSequenceUInt32.write(value.pollRates, into: &buf)
        FfiConverterSequenceString.write(value.attributes, into: &buf)
        FfiConverterSequenceUInt32.write(value.dpiList, into: &buf)
        FfiConverterUInt32.write(value.ledCount, into: &buf)
        FfiConverterBool.write(value.tiltSupported, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDeviceInfo_lift(_ buf: RustBuffer) throws -> DeviceInfo {
    return try FfiConverterTypeDeviceInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDeviceInfo_lower(_ value: DeviceInfo) -> RustBuffer {
    return FfiConverterTypeDeviceInfo.lower(value)
}


public struct DpiStage {
    public var x: UInt32
    public var y: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(x: UInt32, y: UInt32) {
        self.x = x
        self.y = y
    }
}

#if compiler(>=6)
extension DpiStage: Sendable {}
#endif


extension DpiStage: Equatable, Hashable {
    public static func ==(lhs: DpiStage, rhs: DpiStage) -> Bool {
        if lhs.x != rhs.x {
            return false
        }
        if lhs.y != rhs.y {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(x)
        hasher.combine(y)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDpiStage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DpiStage {
        return
            try DpiStage(
                x: FfiConverterUInt32.read(from: &buf), 
                y: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: DpiStage, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.x, into: &buf)
        FfiConverterUInt32.write(value.y, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDpiStage_lift(_ buf: RustBuffer) throws -> DpiStage {
    return try FfiConverterTypeDpiStage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDpiStage_lower(_ value: DpiStage) -> RustBuffer {
    return FfiConverterTypeDpiStage.lower(value)
}


public struct LegacyConfiguration {
    public var dpi: UInt32
    public var pollRate: UInt32
    public var logoOn: Bool
    public var scrollOn: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(dpi: UInt32, pollRate: UInt32, logoOn: Bool, scrollOn: Bool) {
        self.dpi = dpi
        self.pollRate = pollRate
        self.logoOn = logoOn
        self.scrollOn = scrollOn
    }
}

#if compiler(>=6)
extension LegacyConfiguration: Sendable {}
#endif


extension LegacyConfiguration: Equatable, Hashable {
    public static func ==(lhs: LegacyConfiguration, rhs: LegacyConfiguration) -> Bool {
        if lhs.dpi != rhs.dpi {
            return false
        }
        if lhs.pollRate != rhs.pollRate {
            return false
        }
        if lhs.logoOn != rhs.logoOn {
            return false
        }
        if lhs.scrollOn != rhs.scrollOn {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(dpi)
        hasher.combine(pollRate)
        hasher.combine(logoOn)
        hasher.combine(scrollOn)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLegacyConfiguration: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LegacyConfiguration {
        return
            try LegacyConfiguration(
                dpi: FfiConverterUInt32.read(from: &buf), 
                pollRate: FfiConverterUInt32.read(from: &buf), 
                logoOn: FfiConverterBool.read(from: &buf), 
                scrollOn: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: LegacyConfiguration, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.dpi, into: &buf)
        FfiConverterUInt32.write(value.pollRate, into: &buf)
        FfiConverterBool.write(value.logoOn, into: &buf)
        FfiConverterBool.write(value.scrollOn, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLegacyConfiguration_lift(_ buf: RustBuffer) throws -> LegacyConfiguration {
    return try FfiConverterTypeLegacyConfiguration.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLegacyConfiguration_lower(_ value: LegacyConfiguration) -> RustBuffer {
    return FfiConverterTypeLegacyConfiguration.lower(value)
}


public struct Snapshot {
    public var device: DeviceInfo
    public var battery: UInt32?
    public var charging: Bool?
    public var dpi: DpiStage?
    public var stages: [DpiStage]
    public var activeStage: UInt32?
    public var pollRate: UInt32?
    public var idleSeconds: UInt32?
    public var lowBattery: UInt32?
    public var firmware: String?
    public var errors: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(device: DeviceInfo, battery: UInt32?, charging: Bool?, dpi: DpiStage?, stages: [DpiStage], activeStage: UInt32?, pollRate: UInt32?, idleSeconds: UInt32?, lowBattery: UInt32?, firmware: String?, errors: [String]) {
        self.device = device
        self.battery = battery
        self.charging = charging
        self.dpi = dpi
        self.stages = stages
        self.activeStage = activeStage
        self.pollRate = pollRate
        self.idleSeconds = idleSeconds
        self.lowBattery = lowBattery
        self.firmware = firmware
        self.errors = errors
    }
}

#if compiler(>=6)
extension Snapshot: Sendable {}
#endif


extension Snapshot: Equatable, Hashable {
    public static func ==(lhs: Snapshot, rhs: Snapshot) -> Bool {
        if lhs.device != rhs.device {
            return false
        }
        if lhs.battery != rhs.battery {
            return false
        }
        if lhs.charging != rhs.charging {
            return false
        }
        if lhs.dpi != rhs.dpi {
            return false
        }
        if lhs.stages != rhs.stages {
            return false
        }
        if lhs.activeStage != rhs.activeStage {
            return false
        }
        if lhs.pollRate != rhs.pollRate {
            return false
        }
        if lhs.idleSeconds != rhs.idleSeconds {
            return false
        }
        if lhs.lowBattery != rhs.lowBattery {
            return false
        }
        if lhs.firmware != rhs.firmware {
            return false
        }
        if lhs.errors != rhs.errors {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(device)
        hasher.combine(battery)
        hasher.combine(charging)
        hasher.combine(dpi)
        hasher.combine(stages)
        hasher.combine(activeStage)
        hasher.combine(pollRate)
        hasher.combine(idleSeconds)
        hasher.combine(lowBattery)
        hasher.combine(firmware)
        hasher.combine(errors)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSnapshot: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Snapshot {
        return
            try Snapshot(
                device: FfiConverterTypeDeviceInfo.read(from: &buf), 
                battery: FfiConverterOptionUInt32.read(from: &buf), 
                charging: FfiConverterOptionBool.read(from: &buf), 
                dpi: FfiConverterOptionTypeDpiStage.read(from: &buf), 
                stages: FfiConverterSequenceTypeDpiStage.read(from: &buf), 
                activeStage: FfiConverterOptionUInt32.read(from: &buf), 
                pollRate: FfiConverterOptionUInt32.read(from: &buf), 
                idleSeconds: FfiConverterOptionUInt32.read(from: &buf), 
                lowBattery: FfiConverterOptionUInt32.read(from: &buf), 
                firmware: FfiConverterOptionString.read(from: &buf), 
                errors: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: Snapshot, into buf: inout [UInt8]) {
        FfiConverterTypeDeviceInfo.write(value.device, into: &buf)
        FfiConverterOptionUInt32.write(value.battery, into: &buf)
        FfiConverterOptionBool.write(value.charging, into: &buf)
        FfiConverterOptionTypeDpiStage.write(value.dpi, into: &buf)
        FfiConverterSequenceTypeDpiStage.write(value.stages, into: &buf)
        FfiConverterOptionUInt32.write(value.activeStage, into: &buf)
        FfiConverterOptionUInt32.write(value.pollRate, into: &buf)
        FfiConverterOptionUInt32.write(value.idleSeconds, into: &buf)
        FfiConverterOptionUInt32.write(value.lowBattery, into: &buf)
        FfiConverterOptionString.write(value.firmware, into: &buf)
        FfiConverterSequenceString.write(value.errors, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSnapshot_lift(_ buf: RustBuffer) throws -> Snapshot {
    return try FfiConverterTypeSnapshot.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSnapshot_lower(_ value: Snapshot) -> RustBuffer {
    return FfiConverterTypeSnapshot.lower(value)
}


public enum Error: Swift.Error {

    
    
    case Device(message: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeError: FfiConverterRustBuffer {
    typealias SwiftType = Error

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Error {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Device(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Error, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Device(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeError_lift(_ buf: RustBuffer) throws -> Error {
    return try FfiConverterTypeError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeError_lower(_ value: Error) -> RustBuffer {
    return FfiConverterTypeError.lower(value)
}


extension Error: Equatable, Hashable {}




extension Error: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionBool: FfiConverterRustBuffer {
    typealias SwiftType = Bool?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterBool.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterBool.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeDpiStage: FfiConverterRustBuffer {
    typealias SwiftType = DpiStage?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeDpiStage.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeDpiStage.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt32: FfiConverterRustBuffer {
    typealias SwiftType = [UInt32]

    public static func write(_ value: [UInt32], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt32.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt32] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt32]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt32.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeControlRange: FfiConverterRustBuffer {
    typealias SwiftType = [ControlRange]

    public static func write(_ value: [ControlRange], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeControlRange.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ControlRange] {
        let len: Int32 = try readInt(&buf)
        var seq = [ControlRange]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeControlRange.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDeviceInfo: FfiConverterRustBuffer {
    typealias SwiftType = [DeviceInfo]

    public static func write(_ value: [DeviceInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDeviceInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [DeviceInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [DeviceInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDeviceInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDpiStage: FfiConverterRustBuffer {
    typealias SwiftType = [DpiStage]

    public static func write(_ value: [DpiStage], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDpiStage.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [DpiStage] {
        let len: Int32 = try readInt(&buf)
        var seq = [DpiStage]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDpiStage.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_razer_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_razer_core_checksum_method_controller_catalog_json() != 60613) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_razer_core_checksum_method_controller_configure_legacy() != 42615) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_razer_core_checksum_method_controller_devices() != 8093) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_razer_core_checksum_method_controller_dpi() != 34957) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_razer_core_checksum_method_controller_read_control() != 16955) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_razer_core_checksum_method_controller_read_text() != 27540) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_razer_core_checksum_method_controller_set_dpi() != 44752) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_razer_core_checksum_method_controller_set_number() != 50520) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_razer_core_checksum_method_controller_set_stages() != 42245) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_razer_core_checksum_method_controller_snapshot() != 2267) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_razer_core_checksum_method_controller_vendor_id() != 26722) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_razer_core_checksum_method_controller_write_control() != 58716) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_razer_core_checksum_constructor_controller_new() != 37177) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureRazerCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all